import React, { useState, useRef, useCallback } from 'react';
import { useSEO } from '../../utils/seo';
import { ToastContainer, useToast } from '../../hooks/use-toast';
import apiClient from '../../api/axios';

interface ProcessingStatus {
  status: 'idle' | 'uploading' | 'processing' | 'completed' | 'error';
  progress: number;
  message: string;
}

interface LegalDisclaimerProps {
  isOpen: boolean;
  onAccept: () => void;
  onDecline: () => void;
}

const LegalDisclaimer: React.FC<LegalDisclaimerProps> = ({ isOpen, onAccept, onDecline }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white rounded-lg p-6 max-w-2xl mx-4 max-h-[80vh] overflow-y-auto">
        <div className="flex items-center mb-4">
          <div className="flex-shrink-0">
            <svg className="h-6 w-6 text-red-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L3.732 16.5c-.77.833.192 2.5 1.732 2.5z" />
            </svg>
          </div>
          <h3 className="ml-3 text-lg font-medium text-gray-900">
            Legal Disclaimer
          </h3>
        </div>
        
        <div className="mt-2">
          <div className="text-sm text-gray-500 space-y-4">
            <p>
              <strong className="text-red-600">IMPORTANT LEGAL NOTICE:</strong>
            </p>
            <p>
              This tool is designed to remove watermarks from videos, including those generated by Sora and other AI video generation tools. 
              <strong className="text-red-600"> Please be aware of the following legal considerations:</strong>
            </p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Removing watermarks may violate the terms of service of the original video generation platform</li>
              <li>Watermarks often indicate usage rights and attribution requirements</li>
              <li>Removing watermarks without permission may constitute copyright infringement</li>
              <li>You are solely responsible for ensuring your use of this tool complies with all applicable laws and terms of service</li>
              <li>We do not endorse or encourage the unauthorized removal of watermarks</li>
            </ul>
            <p>
              <strong>By using this tool, you acknowledge that:</strong>
            </p>
            <ul className="list-disc list-inside space-y-1 ml-4">
              <li>You have the legal right to modify the video</li>
              <li>You will not use this tool for any illegal purposes</li>
              <li>You understand the potential legal implications</li>
              <li>You will not hold us responsible for any legal consequences</li>
            </ul>
          </div>
        </div>
        
        <div className="mt-6 flex justify-end space-x-3">
          <button
            type="button"
            onClick={onDecline}
            className="px-4 py-2 text-sm font-medium text-gray-700 bg-gray-100 border border-gray-300 rounded-md hover:bg-gray-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500"
          >
            I Decline
          </button>
          <button
            type="button"
            onClick={onAccept}
            className="px-4 py-2 text-sm font-medium text-white bg-red-600 border border-transparent rounded-md hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500"
          >
            I Accept & Continue
          </button>
        </div>
      </div>
    </div>
  );
};

const FileUploadArea: React.FC<{
  onFileSelect: (file: File) => void;
  isProcessing: boolean;
}> = ({ onFileSelect, isProcessing }) => {
  const [isDragOver, setIsDragOver] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragOver(true);
  }, []);

  const handleDragLeave = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragOver(false);
  }, []);

  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragOver(false);
    
    const files = Array.from(e.dataTransfer.files);
    const videoFile = files.find(file => file.type.startsWith('video/'));
    
    if (videoFile) {
      onFileSelect(videoFile);
    }
  }, [onFileSelect]);

  const handleFileInput = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      onFileSelect(file);
    }
  }, [onFileSelect]);

  const handleClick = useCallback(() => {
    fileInputRef.current?.click();
  }, []);

  return (
    <div
      className={`border-2 border-dashed rounded-lg p-8 text-center transition-colors ${
        isDragOver
          ? 'border-blue-400 bg-blue-50'
          : 'border-gray-300 hover:border-gray-400'
      } ${isProcessing ? 'opacity-50 cursor-not-allowed' : 'cursor-pointer'}`}
      onDragOver={handleDragOver}
      onDragLeave={handleDragLeave}
      onDrop={handleDrop}
      onClick={!isProcessing ? handleClick : undefined}
    >
      <input
        ref={fileInputRef}
        type="file"
        accept="video/mp4,video/quicktime,video/x-msvideo,video/webm"
        onChange={handleFileInput}
        className="hidden"
        disabled={isProcessing}
      />
      
      <div className="space-y-4">
        <div className="mx-auto h-12 w-12 text-gray-400">
          <svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 4V2a1 1 0 011-1h8a1 1 0 011 1v2m-9 0h10m-9 0a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V6a2 2 0 00-2-2M9 8h6m-6 4h6m-6 4h6" />
          </svg>
        </div>
        
        <div>
          <p className="text-lg font-medium text-gray-900">
            {isProcessing ? 'Processing...' : 'Upload Video File'}
          </p>
          <p className="text-sm text-gray-500 mt-1">
            Drag and drop your video here, or click to browse
          </p>
          <div className="mt-2 space-y-1">
            <p className="text-xs text-gray-400">
              Supported formats: MP4, MOV, AVI, WebM
            </p>
            <p className="text-xs font-medium text-blue-600">
              📁 Maximum file size: 2MB (current PHP limit)
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

const ProgressBar: React.FC<{ progress: number; message: string }> = ({ progress, message }) => (
  <div className="w-full">
    <div className="flex justify-between text-sm text-gray-600 mb-2">
      <span>{message}</span>
      <span>{Math.round(progress)}%</span>
    </div>
    <div className="w-full bg-gray-200 rounded-full h-2">
      <div
        className="bg-blue-600 h-2 rounded-full transition-all duration-300"
        style={{ width: `${progress}%` }}
      />
    </div>
  </div>
);

export default function WatermarkRemover() {
  const [showDisclaimer, setShowDisclaimer] = useState(true);
  const [acceptedDisclaimer, setAcceptedDisclaimer] = useState(false);
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [processingStatus, setProcessingStatus] = useState<ProcessingStatus>({
    status: 'idle',
    progress: 0,
    message: ''
  });
  const [processedVideoUrl, setProcessedVideoUrl] = useState<string | null>(null);
  const { addToast } = useToast();

  useSEO({
    title: 'Watermark Remover - Remove Sora Video Watermarks | Naqash Thaheem',
    description: 'Remove watermarks from Sora and other AI-generated videos. Professional watermark removal tool with legal compliance.',
    url: '/resources/watermark-remover',
    keywords: ['watermark remover', 'sora watermark', 'video watermark removal', 'AI video processing']
  });

  const validateFile = (file: File): string | null => {
    const validTypes = ['video/mp4', 'video/quicktime', 'video/x-msvideo', 'video/webm'];
    const maxSize = 2 * 1024 * 1024; // 2MB (current PHP limit)

    if (!validTypes.includes(file.type)) {
      return 'Please upload a valid video file (MP4, MOV, AVI, or WebM)';
    }

    if (file.size > maxSize) {
      return 'File size must be less than 2MB due to current PHP configuration. Please compress your video or use a smaller file.';
    }

    return null;
  };

  const handleFileSelect = useCallback((file: File) => {
    const error = validateFile(file);
    if (error) {
      addToast({
        type: 'error',
        title: 'Invalid File',
        description: error
      });
      return;
    }

    setSelectedFile(file);
    setProcessedVideoUrl(null);
  }, [addToast]);

  const handleProcessVideo = async () => {
    if (!selectedFile || !acceptedDisclaimer) return;

    setProcessingStatus({
      status: 'uploading',
      progress: 0,
      message: 'Uploading video...'
    });

    try {
      // Step 1: Upload video
      const formData = new FormData();
      formData.append('video', selectedFile);

      const API_BASE = import.meta.env.VITE_API_URL 
        ? import.meta.env.VITE_API_URL.replace('/api', '') 
        : (import.meta.env.VITE_APP_URL || 'http://localhost:8001');
      const uploadResponse = await fetch(`${API_BASE}/chunked-upload.php`, {
        method: 'POST',
        body: formData,
      });

      if (!uploadResponse.ok) {
        if (uploadResponse.status === 413) {
          throw new Error('File too large. Please upload a video smaller than 50MB.');
        }
        throw new Error(`Upload failed with status: ${uploadResponse.status}`);
      }

      const uploadResult = await uploadResponse.json();

      if (!uploadResult.success) {
        throw new Error(uploadResult.message || 'Upload failed');
      }

      const jobId = uploadResult.data.job_id;

      setProcessingStatus({
        status: 'processing',
        progress: 50,
        message: 'Processing video...'
      });

      // Step 2: Process video
      const processResponse = await apiClient.post(`/watermark-remover/process/${jobId}`);

      const processResult = processResponse.data;

      if (!processResult.success) {
        throw new Error(processResult.message || 'Processing failed');
      }

      // Step 3: Check status and get download URL
      const statusResponse = await apiClient.get(`/watermark-remover/status/${jobId}`);

      const statusResult = statusResponse.data;

      if (!statusResult.success) {
        throw new Error(statusResult.message || 'Status check failed');
      }

      setProcessingStatus({
        status: 'completed',
        progress: 100,
        message: 'Processing completed!'
      });

      setProcessedVideoUrl(statusResult.data.processed_file_url);

      addToast({
        type: 'success',
        title: 'Success',
        description: 'Video processed successfully! You can now download the result.',
      });

    } catch (error: any) {
      console.error('Video processing error:', error);
      
      let errorMessage = 'Processing failed. Please try again.';
      
      if (error.response?.status === 413) {
        errorMessage = 'File too large. Please upload a video smaller than 50MB.';
      } else if (error.response?.data?.message) {
        errorMessage = error.response.data.message;
      } else if (error.message) {
        errorMessage = error.message;
      }
      
      setProcessingStatus({
        status: 'error',
        progress: 0,
        message: errorMessage
      });

      addToast({
        type: 'error',
        title: 'Error',
        description: errorMessage
      });
    }
  };

  const handleDownload = async () => {
    if (!processedVideoUrl) return;

    try {
      // Extract job ID from the processed video URL or store it in state
      // For now, we'll use the URL directly
      const link = document.createElement('a');
      link.href = processedVideoUrl;
      link.download = `processed_${selectedFile?.name || 'video.mp4'}`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    } catch (error) {
      addToast({
        type: 'error',
        title: 'Download Error',
        description: 'Failed to download the processed video. Please try again.'
      });
    }
  };

  const handleReset = () => {
    setSelectedFile(null);
    setProcessedVideoUrl(null);
    setProcessingStatus({
      status: 'idle',
      progress: 0,
      message: ''
    });
  };

  const handleAcceptDisclaimer = () => {
    setAcceptedDisclaimer(true);
    setShowDisclaimer(false);
  };

  const handleDeclineDisclaimer = () => {
    setShowDisclaimer(false);
    // Redirect back to resources page
    window.history.back();
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <ToastContainer />
      
      {/* Legal Disclaimer Modal */}
      <LegalDisclaimer
        isOpen={showDisclaimer}
        onAccept={handleAcceptDisclaimer}
        onDecline={handleDeclineDisclaimer}
      />

      {/* Header */}
      <div className="bg-white border-b border-gray-200">
        <div className="max-w-6xl mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-2xl font-bold text-gray-900">Watermark Remover</h1>
              <p className="text-sm text-gray-600">Remove watermarks from Sora and other AI-generated videos</p>
            </div>
            <div className="flex items-center space-x-4">
              <button
                onClick={() => window.history.back()}
                className="text-gray-600 hover:text-gray-900 px-4 py-2 rounded-lg hover:bg-gray-100 transition-colors duration-200"
              >
                ← Back to Resources
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="max-w-4xl mx-auto px-4 py-8">
        {!acceptedDisclaimer ? (
          <div className="text-center py-12">
            <div className="mx-auto h-12 w-12 text-gray-400 mb-4">
              <svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L3.732 16.5c-.77.833.192 2.5 1.732 2.5z" />
              </svg>
            </div>
            <h3 className="text-lg font-medium text-gray-900 mb-2">Legal Disclaimer Required</h3>
            <p className="text-gray-600">Please accept the legal disclaimer to continue using this tool.</p>
          </div>
        ) : (
          <div className="space-y-8">
            {/* Upload Section */}
            <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
              <h2 className="text-lg font-semibold text-gray-900 mb-4">Upload Video</h2>
              <FileUploadArea
                onFileSelect={handleFileSelect}
                isProcessing={processingStatus.status === 'processing' || processingStatus.status === 'uploading'}
              />
              
              {selectedFile && (
                <div className="mt-4 p-4 bg-gray-50 rounded-lg">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center space-x-3">
                      <div className="flex-shrink-0">
                        <svg className="h-8 w-8 text-red-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 10l4.553-2.276A1 1 0 0121 8.618v6.764a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z" />
                        </svg>
                      </div>
                      <div>
                        <p className="text-sm font-medium text-gray-900">{selectedFile.name}</p>
                        <p className="text-sm text-gray-500">
                          {(selectedFile.size / (1024 * 1024)).toFixed(2)} MB / 50 MB max
                        </p>
                        {selectedFile.size > 50 * 1024 * 1024 && (
                          <p className="text-xs text-red-600 mt-1">
                            ⚠️ File exceeds 50MB limit
                          </p>
                        )}
                      </div>
                    </div>
                    <button
                      onClick={handleReset}
                      className="text-gray-400 hover:text-gray-600"
                    >
                      <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                      </svg>
                    </button>
                  </div>
                </div>
              )}
            </div>

            {/* Processing Section */}
            {(processingStatus.status === 'uploading' || processingStatus.status === 'processing') && (
              <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
                <h2 className="text-lg font-semibold text-gray-900 mb-4">Processing Video</h2>
                <ProgressBar progress={processingStatus.progress} message={processingStatus.message} />
              </div>
            )}

            {/* Results Section */}
            {processingStatus.status === 'completed' && processedVideoUrl && (
              <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
                <h2 className="text-lg font-semibold text-gray-900 mb-4">Processing Complete</h2>
                <div className="space-y-4">
                  <div className="flex items-center justify-between p-4 bg-green-50 rounded-lg">
                    <div className="flex items-center space-x-3">
                      <svg className="h-6 w-6 text-green-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                      </svg>
                      <span className="text-sm font-medium text-green-800">
                        Video processed successfully!
                      </span>
                    </div>
                    <button
                      onClick={handleDownload}
                      className="px-4 py-2 bg-green-600 text-white text-sm font-medium rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500"
                    >
                      Download Processed Video
                    </button>
                  </div>
                  
                  <div className="flex space-x-4">
                    <button
                      onClick={handleReset}
                      className="px-4 py-2 bg-gray-100 text-gray-700 text-sm font-medium rounded-md hover:bg-gray-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500"
                    >
                      Process Another Video
                    </button>
                  </div>
                </div>
              </div>
            )}

            {/* Error Section */}
            {processingStatus.status === 'error' && (
              <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
                <div className="flex items-center space-x-3 p-4 bg-red-50 rounded-lg">
                  <svg className="h-6 w-6 text-red-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                  <div>
                    <p className="text-sm font-medium text-red-800">Processing Failed</p>
                    <p className="text-sm text-red-600">{processingStatus.message}</p>
                  </div>
                </div>
                <div className="mt-4">
                  <button
                    onClick={handleReset}
                    className="px-4 py-2 bg-red-600 text-white text-sm font-medium rounded-md hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500"
                  >
                    Try Again
                  </button>
                </div>
              </div>
            )}

            {/* Action Button */}
            {selectedFile && processingStatus.status === 'idle' && (
              <div className="flex justify-center">
                <button
                  onClick={handleProcessVideo}
                  className="px-8 py-3 bg-blue-600 text-white font-medium rounded-lg hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 transition-colors duration-200"
                >
                  Process Video
                </button>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
