// Verifies the static HTML generated by scripts/prerender.mjs (run by `npm run build`).
// Crawlers that do not execute JavaScript read these files, so they must match the React pages.
import fs from 'node:fs';
import path from 'node:path';
import { test, expect } from './fixtures';
import { pageMeta } from '../src/data/pageMeta';
import { services } from '../src/data/services';
import { caseStudies } from '../src/data/caseStudies';
import { allTools, hubs, toolPath } from '../src/data/tools';
import { careerTools } from '../src/data/careerTools';

const dir = path.resolve(process.cwd(), 'dist/prerender');
const SITE = 'https://naqashthaheem.com';

const expected: { route: string; title: string; description: string }[] = [
  ...Object.values(pageMeta).map((m) => ({ route: m.path, title: m.title, description: m.description })),
  ...services.map((s) => ({ route: `/services/${s.slug}`, title: s.seoTitle, description: s.seoDescription })),
  ...caseStudies.map((c) => ({ route: `/case-studies/${c.slug}`, title: c.seoTitle, description: c.seoDescription })),
  ...Object.values(hubs).map((h) => ({ route: `/resources/${h.hub}`, title: h.seoTitle, description: h.seoDescription })),
  ...allTools.map((t) => ({ route: toolPath(t), title: t.seoTitle, description: t.seoDescription })),
  ...careerTools
    .filter((c) => 'seoTitle' in c && (c as { seoTitle?: string }).seoTitle)
    .map((c) => {
      const cc = c as unknown as { slug: string; seoTitle: string; seoDescription: string };
      return { route: `/resources/${cc.slug}`, title: cc.seoTitle, description: cc.seoDescription };
    }),
];

const decode = (s: string) => s.replace(/&quot;/g, '"').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&amp;/g, '&');

test.describe('Prerendered HTML', () => {
  test.skip(!fs.existsSync(dir), 'run `npm run build` first (dist/prerender missing)');

  test('every marketing and tool route has a correct static page', () => {
    const problems: string[] = [];
    for (const { route, title, description } of expected) {
      const file = route === '/' ? path.join(dir, 'index.html') : path.join(dir, `${route.slice(1)}.html`);
      if (!fs.existsSync(file)) {
        problems.push(`${route}: missing ${path.relative(process.cwd(), file)}`);
        continue;
      }
      const html = fs.readFileSync(file, 'utf8');
      const got = (re: RegExp) => decode(html.match(re)?.[1] ?? '');
      if (got(/<title>([\s\S]*?)<\/title>/) !== title) problems.push(`${route}: title "${got(/<title>([\s\S]*?)<\/title>/)}"`);
      if (got(/<meta name="description" content="([^"]*)"/) !== description) problems.push(`${route}: description differs`);
      if (got(/<link rel="canonical" href="([^"]*)"/) !== `${SITE}${route}`) problems.push(`${route}: canonical`);
      if ((html.match(/<h1[\s>]/g) || []).length !== 1) problems.push(`${route}: h1 count ${(html.match(/<h1[\s>]/g) || []).length}`);
      if (!html.includes('data-prerender')) problems.push(`${route}: no prerendered content`);
      if (html.includes('<noscript>')) problems.push(`${route}: stray noscript block`);
      if (/aggregateRating/i.test(html)) problems.push(`${route}: aggregateRating`);
      for (const [, json] of html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)) {
        try {
          JSON.parse(json);
        } catch {
          problems.push(`${route}: invalid JSON-LD`);
        }
      }
      const text = html.replace(/<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>|<[^>]+>/g, ' ');
      const words = text.split(/\s+/).filter(Boolean).length;
      if (words < 80) problems.push(`${route}: only ${words} words of crawlable text`);
    }
    expect(problems, problems.join('\n')).toEqual([]);
  });
});
